var $lang = {};
$lang.ru = {
    'HOTELS' : 'Отели',
    'Hotel' : 'Отель',
    'Hall' : 'Зал',
    'nohotels' : 'Для Вашей компании еще не назначены отели.',
    'sessionexpired' : 'Ваш сеанс работы с системой истёк. Пожалуйста, авторизуйтесь заново.',
    'mygroup' : 'Моя группа',
    'changepass' : 'Сменить пароль',
    'searchbynumber' : 'Поиск мероприятия по номеру',
    'search' : 'Поиск',
    'Events' : 'Мероприятия',
    'events5': 'мероприятий',
    'Companies' : 'Компании',
    'Requests' : 'Запросы',
    'Report' : 'Отчёт',
    'Analytics' : 'Аналитика',
    'Exit' : 'Выход',
    'Name' : 'Название',
    'Address' : 'Адрес',
    'Contactnumber' : 'Контактный телефон',
    'Site' : 'Сайт',
    'Processingcomplexity' : 'Сложность обработки',
    'Types': 'Типы',
    'Typeofbusiness' : 'Тип бизнеса',
    'Typeofbusiness1': 'Типы бизнеса',
    'Typeofevents': 'Типы мероприятий',
    'Economysegments': 'Сегменты экономики',
    'Typeofbusiness2': 'Типы бизнеса, сегменты экономики и типы мероприятий',
    'Description' : 'Описание',
    'Logo' : 'Логотип',
    'Previousweek' : 'Предыдущая неделя',
    'Nextweek' : 'Следующая неделя',
    'Colorcoding' : 'Обозначение цветов',
    'nohotelsavail' : 'За данный период нет доступных отелей.',
    'Login' : 'Логин',
    'Password' : 'Пароль',
    'Signin' : 'Вход',
    'Register' : 'Регистрация',
    'Forgotpass' : 'Забыли пароль?',
    'Currentpassword' : 'Текущий пароль',
    'Newpassword' : 'Новый пароль',
    'Newpasswordagain' : 'Новый пароль повторно',
    'Change' : 'Change',
    'Chooseperiod' : 'Выберите период',
    'Sortby' : 'Сортировать по',
    'Dateof' : 'Дате',
    'manager' : 'Менеджеру',
    'Includecolumns' : 'Включить колонки в отчёт',
    'Eventtype' : 'Тип мероприятия',
    'Conferencehall' : 'Конференц зал',
    'Numberpeople' : 'Количество людей',
    'Food' : 'Еда',
    'Contactorganizer' : 'Контакты организатора',
    'Organizer' : 'Организатор',
    'Export' : 'Выгрузить',
    'Confirmaction' : 'Подтвердите действие',
    'Error' : 'Ошибка',
    'Yes' : 'Да',
    'No' : 'Нет',
    'Noevents' : 'Нет мероприятий',
    'AdditionalInformation' : 'Дополнительная информация',
    'Notassigned' : 'Не назначен',
    'Numberrooms' : 'Количество номеров',
    'Numberhalls' : 'Количество залов',
    'waccommodation': 'с проживанием',
    'wronglogin' : 'Неверный логин или пароль',
    'Accountnotactivated' : 'Account not activated',
    'Entercurrentpassword' : 'Enter your current password',
    'Invalidcurrentpassword' : 'Invalid current password',
    'Enternewpassword' : 'Enter new password',
    'Passwordmust6long' : 'A new password must be 6 or more characters long.',
    'Specifycurrentpassagain' : 'Specify the current password again.',
    'Newpassnotmatch' : 'New passwords do not match.',
    'Passwordchanged' : 'Пароль изменён!',
    'NoEventForOrg' : 'Не найдены мероприятия этого организатора.',
    'from' : 'из',
    'meters' : 'метров',
    'ofspaceoccupied' : 'площадей занято',
    'Occupiedarea' : 'Занятая площадь',
    'Space' : 'Площадь',
    'Filter' : 'Фильтр',
    'Halloccupancy' : 'Загруженность залов',
    'Ratiooccupied': 'Соотношение занятой к общей площади',
    'Busy' : 'Занято',
    'Free': 'Свободно',
    'Dynamics' : 'Сравнение',
    'Dynamics1' : 'Сравнение по дням',
    'Numbereventsoccupiedarea': 'Количество мероприятий, занятая площадь и продолжительность мероприятий',
    'Lines': 'Линии',
    'Stacked': 'Совместно',
    'Separate': 'Раздельно',
    'Bars' : 'Столбцы',
    'Restore': 'Восстановить',
    'Saveas': 'Сохранить как',
    'Quantity': 'Количество',
    'Space': 'Площадь',
    'Rating': 'Рейтинг',
    'TOP10org': 'ТОП10 организаторов',
    'TOP10halls': 'TOП10 залов',
    'Numberevents': 'Количество мероприятий',
    'Eventsheld': 'Проведенных мероприятий',
    'Numberdays': 'Количество дней',
    'Duration': 'Кол-во дней',
    'Averageduration': 'Средняя продолжительность',
    'Averageoccupiedarea': 'Средняя площадь',
    'Averagehotelload': 'Средняя загрузка отеля',
    'Marketshare': 'Доля рынка',
    'Averagevalue': 'Среднее значение',
    'Loadbyday': 'Средняя нагрузка по дням недели',
    'Averagepeopleperday': 'Среднее количество людей по дням недели',
    'allhotels': 'всех отелей',
    'Actualarea': 'Актуальная доля',
    'Fairarea': 'Справедливая доля',
    'Difference': 'Разница',
    'Sharesmarket' : 'Доли рынка отелей',
    'Overview': 'Обзор',
    'Hotelanalysis': 'Анализ отеля',
    'hasNotes' : 'Есть заметки',
    'hasSite' : 'Есть сайт мероприятия',
    'hasPhotos' : 'Есть фотографии',
    'hasManager' : 'Назначен менеджер',
    'appointed' : 'Назначен',
    'day1' : 'день',
    'day2' : 'дня',
    'day5' : 'дней',
    'cal_mon' : 'ПН',
    'cal_tue' : 'ВТ',
    'cal_wed' : 'СР',
    'cal_thu' : 'ЧТ',
    'cal_fri' : 'ПТ',
    'cal_sat' : 'СБ',
    'cal_sun' : 'ВС'
};
//Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday

$lang.en = {
    'HOTELS': 'Hotels',
    'Hotel' : 'Hotel',
    'Hall' : 'Hall',
    'nohotels': 'No hotels have been assigned to your company yet.',
    'sessionexpired': 'Your session has expired. Please login again.',
    'mygroup': 'My group',
    'changepass': 'Change password',
    'searchbynumber': 'Search for events by number',
    'search': 'Search',
    'Events': 'Events',
    'events5': 'events',
    'Companies': 'Companies',
    'Requests': 'Requests',
    'Report': 'Report',
    'Analytics': 'Analytics',
    'Exit': 'Sign out',
    'Name': 'Name',
    'Address': 'Address',
    'Contactnumber': 'Phone',
    'Site': 'Site',
    'Processingcomplexity': 'Processing complexity',
    'Types': 'Types',
    'Typeofbusiness': 'Type of business',
    'Typeofbusiness1': 'Type of business',
    'Typeofevents': 'Types of events',
    'Economysegments': 'Economy Segments',
    'Typeofbusiness2': 'Business Types, Economy Segments, and Event Types',
    'Description': 'Description',
    'Logo': 'Logo',
    'Previousweek': 'Previous week',
    'Nextweek': 'Next week',
    'Colorcoding': 'Color coding',
    'nohotelsavail': 'There are no hotels available for this period.',
    'Login': 'Login',
    'Password': 'Password',
    'Signin': 'Sign in',
    'Register': 'Register',
    'Forgotpass': 'Forgot password?',
    'Currentpassword': 'Current password',
    'Newpassword': 'New password',
    'Newpasswordagain': 'New password again',
    'Change': 'Change',
    'Chooseperiod': 'Choose for the period',
    'Sortby': 'Sort by',
    'Dateof': 'Date of',
    'manager': 'manager',
    'Includecolumns': 'Include columns in the report',
    'Eventtype': 'Event type',
    'Conferencehall': 'Conference hall',
    'Numberpeople': 'Number of people',
    'Food': 'Food',
    'Contactorganizer': 'Contact organizer',
    'Organizer': 'Organizer',
    'Export': 'Export',
    'Confirmaction': 'Confirm action',
    'Error': 'Error',
    'Yes': 'Yes',
    'No': 'No',
    'Noevents': 'No events',
    'AdditionalInformation': 'Additional Information',
    'Notassigned': 'Not assigned',
    'Numberrooms': 'Number of rooms',
    'Numberhalls': 'Number of halls',
    'waccommodation': 'with accommodation',
    'wronglogin': 'Wrong login or password',
    'Accountnotactivated': 'Account not activated',
    'Entercurrentpassword': 'Enter your current password',
    'Invalidcurrentpassword': 'Invalid current password',
    'Enternewpassword': 'Enter new password',
    'Passwordmust6long': 'A new password must be 6 or more characters long.',
    'Specifycurrentpassagain': 'Specify the current password again.',
    'Newpassnotmatch': 'New passwords do not match.',
    'Passwordchanged': 'Password changed!',
    'NoEventForOrg' : 'No events were found by this organizer.',
    'from' : 'from',
    'meters' : 'meters',
    'ofspaceoccupied' : 'of space occupied',
    'Occupiedarea' : 'Occupied area',
    'Space' : 'Space',
    'Filter' : 'Filter',
    'Halloccupancy' : 'Hall occupancy',
    'Ratiooccupied': 'Ratio occupied to the total area',
    'Busy' : 'Busy',
    'Free': 'Free',
    'Dynamics' : 'Comparison',
    'Dynamics1' : 'Day comparison',
    'Numbereventsoccupiedarea': 'Number of events and occupied area',
    'Lines': 'Lines',
    'Stacked': 'Stacked',
    'Separate': 'Separate',
    'Bars' : 'Bars',
    'Restore': 'Restore',
    'Saveas': 'Save as',
    'Quantity': 'Quantity',
    'Space': 'Space',
    'Rating': 'Rating',
    'TOP10org': 'TOP10 organizers',
    'TOP10halls': 'TOP10 halls',
    'Numberevents': 'Number of events',
    'Numberdays': 'Number of days',
    'Eventsheld': 'Events held',
    'Duration': 'Duration',
    'Averageduration': 'Average duration',
    'Averageoccupiedarea': 'Average area',
    'Averagehotelload': 'Average hotel load',
    'Marketshare': 'Market share',
    'Averagevalue': 'Average value',
    'Loadbyday': 'Average load by day',
    'Averagepeopleperday': 'Average number of people by day',
    'allhotels': 'all hotels',
    'Actualarea': 'Current share',
    'Fairarea': 'Fair area',
    'Difference': 'Difference',
    'Sharesmarket' : 'Shares of the hotel market',
    'Overview': 'Overview',
    'Hotelanalysis': 'Hotel Analysis',
    'hasNotes' : 'Have notes',
    'hasSite' : 'There is an event site',
    'hasPhotos' : 'There are photos',
    'hasManager' : 'Manager appointed',
    'appointed' : 'appointed',
    'day1' : 'day',
    'day2' : 'days',
    'day5' : 'days',
    'cal_mon': 'MO',
    'cal_tue': 'TU',
    'cal_wed': 'WE',
    'cal_thu': 'TH',
    'cal_fri': 'FR',
    'cal_sat': 'SA',
    'cal_sun': 'SU'
};